/**
 * OdeApp
 * REST API backend for OdeApp
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdeApp);
  }
}(this, (expect, OdeApp) => {
  let instance;

  beforeEach(() => {
    instance = new OdeApp.User();
  });

  const getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    return object[property];
  };

  const setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('User', () => {
    it('should create an instance of User', () => {
      // uncomment below and update the code to test User
      // var instane = new OdeApp.User();
      // expect(instance).to.be.a(OdeApp.User);
    });

    it('should have the property username (base name: "username")', () => {
      // uncomment below and update the code to test the property username
      // var instane = new OdeApp.User();
      // expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', () => {
      // uncomment below and update the code to test the property password
      // var instane = new OdeApp.User();
      // expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', () => {
      // uncomment below and update the code to test the property firstName
      // var instane = new OdeApp.User();
      // expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', () => {
      // uncomment below and update the code to test the property lastName
      // var instane = new OdeApp.User();
      // expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', () => {
      // uncomment below and update the code to test the property email
      // var instane = new OdeApp.User();
      // expect(instance).to.be();
    });
  });
}));
